services:
  mysql:
    container_name: mysql-db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 7545590000
      MYSQL_DATABASE: jwt_security
      MYSQL_USER: root
      MYSQL_PASSWORD: 7545590000
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mysql-network
    restart: unless-stopped

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8080:80"
    networks:
      - mysql-network
    restart: unless-stopped

networks:
  mysql-network:
    driver: bridge

volumes:
  mysql-data:
